### ISSUE TITLE
Get error trying to run it

### ISSUE THREAD

**Issue by nikivdev** [lorentzca/alfred-circleci-workflow#3]
```bash
[2018-05-29 22:11:44][ERROR: input.scriptfilter] Code 2: /bin/bash: line 2: =: command not found
flag needs an argument: -f
Usage of ./alfred-circleci-workflow:
  -f string
    	Search Filter (default "reponame, branch, username, status...")
  -t string
    	CirclCI Token (default "secret")
```

I have saved the API key into Keychain before that.

**Comment by lorentzca** [comment]
I'm sorry for the delay in replying your comment.

If you do not enter any characters, that error will occur.

<img width="928" alt="2019-02-11 11 09 05" src="https://user-images.githubusercontent.com/1402528/52543498-80a05100-2ded-11e9-8c13-5684afde80ea.png">

Search is started if you enter some characters.

Thank you.
